---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ tailscale_hostname | default(inventory_hostname) }}"

- name: Install base packages
  ansible.builtin.apt:
    name: "{{ base_packages }}"
    state: present
    update_cache: true
